coverage:
  notify:
    slack:
      default:
        url: "https://hooks.slack.com/services/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"
        threshold: 0%
        only_pulls: false
        branches: null
        flags: null
        paths: null
